config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'users#show'
  resources :users do
    resources :posts
  end

  get 'users/:id/followers' => 'users#followers'
  get 'users/:id/following' => 'users#following'

  resources :relationships, only: %i[create destroy]
  resources :streams, only: :index

  resources :conversations do
    resources :messages
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  scope :between, -> (sender_id, recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id
    =?) OR (conversations.recipient_id = ? AND conversations.sender_id
    =?)", sender_id,recipient_id, recipient_id, sender_id)
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :description, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts

  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'follower_id',
                                  dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'followed_id',
                                   dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower


  validates :username, uniqueness: true, presence: true
  validates :age, numericality: { greater_than_or_equal_to: 1 }

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email username name surname age])
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  def index
    @users = User.all
    @conversations = Conversation.all
  end

  def create
    if Conversation.between(params[:sender_id], params[:recipient_id])
           .present?
      @conversation = Conversation.between(params[:sender_id],
                                           params[:recipient_id]).first
    elsif Conversation.between(params[:recipient_id], params[:sender_id])
              .present?
      @conversation = Conversation.between(params[:recipient_id],
                                           params[:sender_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end
    redirect_to conversation_messages_path(@conversation)
  end


  private

  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    @messages = @conversation.messages
    if @messages.length > 10
      @over_ten = true
      @messages = @messages[-10..-1]
    end
    if params[:m]
      @over_ten = false
      @messages = @conversation.messages
    end
    if @messages.last
      if @messages.last.user_id != current_user.id
        @messages.last.read = true;
      end
    end
    @message = @conversation.messages.new
  end

  def new
    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)
    if @message.save
      redirect_to conversation_messages_path(@conversation)
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    current_user.posts.create(posts_params)

    redirect_to root_path
  end

  private

  def posts_params
    params.require(:post).permit(:description)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  def index
    @all_news = Post.where(user_id: current_user.following.pluck(:id))
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user!

  def show
    @user = (User.preload(:posts).find(params[:id]) if params[:id]) || current_user
    @on_my_page = @user.id == current_user.id
  end

  def index
    @users = User.where.not(id: current_user.id).shuffle
  end

  def followers
    @user = (User.find(params[:id]) if params[:id]) || current_user
  end

  def following
    @user = (User.find(params[:id]) if params[:id]) || current_user
  end

  private

  def set_user!
    @user = User.find[:username] if params[:username]
  end

  def permitted_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/conversations/index.html.erb
<ul class="list-group">
  <li class="list-group-item active">Mailbox</li>

  <li class="list-group-item">
    <% @conversations.each do |conversation| %>
      <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
        <% if conversation.sender_id == current_user.id %>
          <% recipient = User.find(conversation.recipient_id) %>
        <% else %>
          <% recipient = User.find(conversation.sender_id) %>
        <% end %>
        <li class="list-group-item">
        <%= link_to recipient.username, conversation_messages_path(conversation) %>
        </li>
      <% end %>
    <% end %>
  </li>
</ul>
<br/>

<ul class="list-group">
  <li class="list-group-item active">All Users</li>
  <li class="list-group-item">
    <% @users.each do |user| %>
      <% if user.id != current_user.id %>
        <li class="list-group-item">
          <p class="username__style"><%= user.username %></p> <%= link_to 'Message', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post' %>
        </li>
      <% end %>
    <% end %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialNetwork</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  </head>

  <body>
    <%= render partial: 'shared/navigation_bar' %>
    <div class="container main__section">
      <div class="row">
        <div class="col-12">
          <%= yield %>
        </div>
      </div>
    </div>

  <%= render partial: 'shared/footer_bar' %>
  </body>
</html>

app/views/messages/index.html.erb
<% if @over_ten %>
  <%= link_to 'Show Previous', '?m=all' %>
<% end %>

<div class="message__wrapper">
  <% @messages.each do |message| %>
    <% if message.body %>
      <% user = User.find(message.user_id) %>
      <div class="section__message">
        <div>
          <strong><%= user.username %></strong>
          <%= message.message_time %>
        </div>
        <div class="list">
          <div class="item">
            <%= message.body %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<%= form_for [@conversation, @message] do |f| %>
  <div class="send__message">
    <div class="field">
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <%= f.text_field :user_id, value: current_user.id, type: "hidden" %>
    <div>
      <%= f.submit "Add Reply", class: "btn btn-primary button__message" %>
    </div>
  </div>
<% end %>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('shared/unfollow')) %>");
$("#followers").html('&nbsp; &nbsp; &nbsp;<%= @user.followers.count %> ');

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('shared/follow')) %>");
$("#followers").html('&nbsp; &nbsp; &nbsp;<%= @user.followers.count %> ');

app/views/shared/_all_user_list.html.erb
<ul class="list-group">
  <li class="list-group-item active">All users list</li>
  <% @users.each do |user| %>
      <li class="list-group-item"><%= link_to user.name, user_path(user) %></li>
  <% end %>
</ul>

app/views/shared/_conversation.html.erb
<div class="ui segment">
  <h3>Mailbox</h3>

  <div class="ui list">
    <div class="item">
      <% @conversations.each do |conversation| %>
        <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
          <% if conversation.sender_id == current_user.id %>
            <% recipient = User.find(conversation.recipient_id) %>
          <% else %>
            <% recipient = User.find(conversation.sender_id) %>
          <% end %>
          <%= link_to recipient.first_name, conversation_messages_path(conversation) %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="ui segment">
  <h3>All Users</h3>
  <div class="ui list">
    <% @users.each do |user| %>
      <% if user.id != current_user.id %>
        <div class="item">
          <%= user.first_name %> <%= link_to 'Message me! ', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post' %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit " Follow  ", class: "btn btn-primary follow__button" %>
<% end %>

app/views/shared/_follow_form.html.erb
<div id="follow_form" >
  <% if current_user.following?(@user) %>
    <%= render 'shared/unfollow' %>
  <% else %>
    <%= render 'shared/follow' %>
  <% end %>
</div>

app/views/shared/_footer_bar.html.erb
<footer class="footer ">
  <div class="wrapper container">
    <div class="footer__item">
      <div class="footer__logo">
        Social Network
      </div>
      <nav class="footer__nav">
        <ul class="footer_menu">
          <li class="footer__menu-item">
            <h3 class="footer__menu-title">
              Company
            </h3>
          </li>
          <li class="footer__menu-item">
            <a href="#!" class="footer__menu-link">About</a>
          </li>
          <li class="footer__menu-item">
            <a href="#!" class="footer__menu-link">Team</a>
          </li>
          <li class="footer__menu-item">
            <a href="#!" class="footer__menu-link">Carrers</a>
          </li>
          <li class="footer__menu-item">
            <a href="#!" class="footer__menu-link">Privacy Policy</a>
          </li>
        </ul>

        <ul class="footer_menu">
          <li class="footer__menu-item">
            <h3 class="footer__menu-title">
              Location
            </h3>
          </li>
          <li class="footer__menu-item">
            <a href="#!" class="footer__menu-link">About</a>
          </li>
          <li class="footer__menu-item">
            <a href="#!" class="footer__menu-link">Team</a>
          </li>
          <li class="footer__menu-item">
            <a href="#!" class="footer__menu-link">Carrers</a>
          </li>
          <li class="footer__menu-item">
            <a href="#!" class="footer__menu-link">Privacy Policy</a>
          </li>
        </ul>

        <ul class="footer_menu">
          <li class="footer__menu-item">
            <h3 class="footer__menu-title">
              Social Media
            </h3>
          </li>
          <li class="footer__menu-item">
            <a href="#!" class="footer__menu-link">Facebook</a>
          </li>
          <li class="footer__menu-item">
            <a href="#!" class="footer__menu-link">Team</a>
          </li>
          <li class="footer__menu-item">
            <a href="#!" class="footer__menu-link">Carrers</a>
          </li>
          <li class="footer__menu-item">
            <a href="#!" class="footer__menu-link">Privacy Policy</a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</footer>

app/views/shared/_navigation_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between mb-4">
  <a class="navbar-brand" href="/">Social Network</a>

  <% if current_user %>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to current_user.username, root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Users', users_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Conversations', conversations_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Streams', streams_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active custom-item">
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  <% end %>
</nav>

app/views/shared/_new_post.html.erb
<%= form_for([@user, @user.posts.build]) do |f| %>
  <h3>Add some post</h3>
  <div class="form-grid">
    <%= f.text_area :description,
                    required: true,
                    autofocus: true,
                    class: 'textarea__main' %>
    <%= f.submit('Create post', class: 'btn btn-primary') %>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<div class="stats">
  <strong id="following">
    <%= @user.following.count %>
  </strong>

  <%= link_to 'following', params[:id] ? "#{params[:id]}/following" : "users/#{current_user.id}/following" %>

  <strong id="followers">
    &nbsp; &nbsp; &nbsp;<%= @user.followers.count %>
  </strong>

  <%= link_to 'followers', params[:id] ? "#{params[:id]}/followers" : "users/#{current_user.id}/followers" %>
</div>

app/views/shared/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-danger follow__button" %>
<% end %>

app/views/streams/index.html.erb
<ul>
<li class="list-group-item active">All news </li>
  <% @all_news.each do |news| %>
    <li class="list-group-item list-group-item-primary"><%= news.description %></li>
    <li class="list-group-item list-group-item-warning"><%= news.user.username %></li>
<% end %>
</ul>

app/views/users/followers.html.erb
<ul class="list-group">
  <% if @user.followers.size.eql?(0) %>
    <li class="list-group-item active">No followers yet</li>
  <% else %>
    <li class="list-group-item active">All followers list</li>
  <% end %>

  <% @user.followers.each do |user| %>
    <li class="list-group-item"><%= link_to user.name, user_path(user) %></li>
  <% end %>
</ul>

app/views/users/following.html.erb
<ul class="list-group">
  <% if @user.following.size.eql?(0) %>
    <li class="list-group-item active">No following yet</li>
  <% else %>
    <li class="list-group-item active">All following list</li>
  <% end %>

  <% @user.following.each do |user| %>
    <li class="list-group-item"><%= link_to user.name, user_path(user) %></li>
  <% end %>
</ul>

app/views/users/index.html.erb
<%= render partial: 'shared/all_user_list' %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <%= image_tag(@user.image_path, {class: "style__image"}) %>
    </div>
    <div class="col-sm-4 m-4">
      <h3><%= @user.name %> <%= @user.surname %></h3>
      <h4>Age: <%= @user.age %></h4>
      <br>
      <div>
        <%= render partial: 'shared/stats' %>
      </div>

      <% unless @on_my_page %>
        <div class="container-fluid">
          <div class="row">
            <%= render 'shared/follow_form' %>
            <%= link_to 'Message', conversations_path(sender_id: current_user.id, recipient_id: params[:id]), method: 'post', class: 'btn btn-primary ml-3' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<br>
<% if @on_my_page %>
  <%= render partial: 'shared/new_post' %>
<% end %>

<br>

<ul class="list-group">
  <li class="list-group-item active">My posts</li>
  <% if @user.posts.size.zero? %>
    <li class="list-group-item">No posts yet</li>
  <% else %>
    <% @user.posts.distinct.reverse_each do |post| %>
      <li class="list-group-item">
        <p><%= post.description %></p>
        <p><%= post.created_at.strftime("%H:%M %d.%m.%Y") %></p>
      </li>
    <% end %>
  <% end %>
</ul>